### ISSUE TITLE
Editor not rendering

### ISSUE THREAD

**Issue by loriRyanp** [Bjornmamman/Our.Umbraco.SimpleTreeMenu#11]
Hey guys
Sorry to bother you again but still having trouble getting this implemented.

I have created a doctype called menuNode with the following properties
**Properties**
title | textbox 
newWindow | true /false
backgroundImage | Media Picker
linkedUrl | Textbox
linkedContent | Linked Content - Multinode Treepicker with 
Node Type: Content
allowed docTypes: of standard page / home and min number of items 1
**Is element : True**

I then created a datatype called (BM) Tree Menu 
property editor: simpleTreemenu
doctype menu node
levels 3

I then put the bm tree menu on my home node however I get the following
![image](https://user-images.githubusercontent.com/59826692/85063357-efd84300-b1a1-11ea-8a94-df3ec4ec2fa7.png)

There are some angular errors in the console:
rror: [$compile:multidir] Multiple directives [uiTree, uiTree] asking for 'uiTree' controller on: <div ui-tree="treeOptions" class="angular-ui-tree" data-max-depth="model.config.levels">

I am on umbraco 8.6.2

Appreciate any help thanks

**Comment by madsoulswe** [comment]
It looks like the uiTree directive is registered twice.
Check if you can find ".directive('uiTree'," twice somewhere or check the console if this file is loaded twice:
https://github.com/Bjornmamman/Our.Umbraco.SimpleTreeMenu/blob/master/src/TreeMenu/App_Plugins/SimpleTreeMenu/Js/lib/treemenu.js
