### ISSUE TITLE
On Umbraco 8  - Editor without permission to the Settings section cannot edit a SimpleTreeMenu based property

### ISSUE THREAD

**Issue by doronuziel71** [Bjornmamman/Our.Umbraco.SimpleTreeMenu#16]
Hi all,
When an editor clicks on the **Edit** button to open the editting dialog, the Login screen  shows.

The problem seems to relate to the usage of `contentTypeResource` which calls the `ContentTypeController `, which is restricted as follows:
`[UmbracoTreeAuthorize(Constants.Trees.DocumentTypes)]`

Probably the usage of the `entityResource` which utilizes the `EntityController `should be considered. 
Unfurtunately the `getAll` function return items with empty alias, so its not that easy to and probably requires a revision of the unique-id being used 😞.

**Comment by DarkSummon** [comment]
Thanks @doronuziel71, I noticed this today too. Caused me a headache trying to understand what the cause was! Let me know if you find a workaround or solution, perhaps before an official release. Thanks.

**Comment by stefankip** [comment]
According to the release notes this was fixed in 1.1 right?
