### ISSUE TITLE
Any idea why the empty-check for RTEs doesn't work in name templates?

### ISSUE THREAD

**Issue by hfloyd** [Bjornmamman/Our.Umbraco.SimpleTreeMenu#58]
I have an RTE on the "Menu Item" Element used for the menu. When I create a name template using that along the lines of:
 `{{!! MyRte ? '[Has RT]' : '[No RT]' }}` 
it ALWAYS displays `[Has RT]`.

I tried several different variations without success.

**Comment by madsoulswe** [comment]
Hi! Sorry for all late responses. Have been super busy!

Not sure actually the template uses native umbraco angularfilters. 
But it might be the new json-format that Umbraco stores richtext in.

It's something like this:
```
{
    "markup": "<p>......",
    "blocks" : ....,
}
```

**Comment by hfloyd** [comment]
@madsoulswe you were correct - This works properly:

`{{!! MyRte["markup"] ? '[Has RT]' : '[No RT]' }}`

Thanks again!
