### ISSUE TITLE
Tree Menu in Umbraco 8.4.0

### ISSUE THREAD

**Issue by loriRyanp** [Bjornmamman/Our.Umbraco.SimpleTreeMenu#6]
I have a multi node site. i.e. Home with pages underneath it and website configuration where I have placed the tree to manage navigation. However I cannot select anything keep getting 

Request error: The URL returned a 404 (not found):
/umbraco/backoffice/UmbracoApi/Content/GetEmpty

From the logs
{"@t":"2020-01-23T16:51:28.3209538Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"Website Configuration","ContentId":1108,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":10772,"ProcessName":"w3wp","ThreadId":113,"AppDomainId":61,"AppDomainAppId":"LMW3SVC4ROOT","MachineName":"xxxxxx","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"4414c0d6-6bb3-453e-b5ab-0510df6dfca5"}

**Comment by HTDL-Andrew** [comment]
It's not really clear from the instructions, you need to create a document type called Menu Node with the alias menuNode with the controls shown in the screenshot, title link etc.

[View screen shot](https://our.umbraco.com/media/wiki/279949/637207217614880925_menunodejpg.JPG)

**Comment by madsoulswe** [comment]
You can name the doctype what every you like. 
The doctype-alias i set in the datatype editor. Here:
https://our.umbraco.com/packages/website-utilities/simpletreemenu/#package-gallery-7

But the default value is set to "menuNode".

I will:
- Add an error message when the it cant find the doctype 
- Add a doctype-picker to the datatype.

**Comment by HTDL-Andrew** [comment]
As long as people know they need to create a doctype I don't think it matters. Great package by the way!

**Comment by madsoulswe** [comment]
Fixed in version 0.2.2

**Comment by loriRyanp** [comment]
Thanks - looking forward to retrying the package
