### ISSUE TITLE
Umbraco 8.6.1

### ISSUE THREAD

**Issue by HTDL-Andrew** [Bjornmamman/Our.Umbraco.SimpleTreeMenu#7]
When I install the package the dropdown doesn't populate with the available data types, just displays the tick mark (See screenshot).

https://www.dropbox.com/s/o08tuh3rldp76ib/error.png?dl=0

Many Thanks

**Comment by madsoulswe** [comment]
Hello!

Have you ticked in the "Is element type" on you Documenttype.

![image](https://user-images.githubusercontent.com/7071187/82436054-80cdd880-9a95-11ea-9606-45f360b791ae.png)

**Comment by HTDL-Andrew** [comment]
Sorry no I haven’t, I’ll do this now.

Many Thanks

Andrew



 <https://htmlsig.com/t/0000001BVBRD4>

Andrew Hopkins / Head of Digital 
ah@htdl.co.uk <mailto:ah@htdl.co.uk>

HTDL Ltd 
01564797420 
6 Ardent Court, William James Way 
Henley in Arden, Warwickshire B95 5GF 
htdl.co.uk <http://htdl.co.uk/>

 <https://htmlsig.com/t/0000001BZ05N4>   <https://htmlsig.com/t/0000001BYDAB2> 




Top 50 design agencies in the UK
Design Business Association member
Recommended Agency Register 2019
ISO 9001 accredited design consultancy

**Comment by HTDL-Andrew** [comment]
Thank you Dennis,

Sorry, are there any additional references or using statements I need as well on the template?

Thanks
A

 <https://htmlsig.com/t/0000001BVBRD4>

Andrew Hopkins / Head of Digital 
ah@htdl.co.uk <mailto:ah@htdl.co.uk>

HTDL Ltd 
01564797420 
6 Ardent Court, William James Way 
Henley in Arden, Warwickshire B95 5GF 
htdl.co.uk <http://htdl.co.uk/>

 <https://htmlsig.com/t/0000001BZ05N4>   <https://htmlsig.com/t/0000001BYDAB2> 




Top 50 design agencies in the UK
Design Business Association member
Recommended Agency Register 2019
ISO 9001 accredited design consultancy
