### ISSUE TITLE
Lose the Name textbox

### ISSUE THREAD

**Issue by stefankip** [Bjornmamman/Our.Umbraco.SimpleTreeMenu#9]
I don't get why there's a textbox with the caption "Enter a name...". Why do I have to enter a name, when I already enter the Title property inside the item?
I think it should use a template to show the item's name, just like Nested Content does. I don't want my client to enter the link text twice :-)

**Comment by stefankip** [comment]
Just fiddled a bit with the view and controller and this is how it could look:

![image](https://user-images.githubusercontent.com/46313552/82675489-2d9a8800-9c45-11ea-8879-61686f10407c.png)

**Comment by madsoulswe** [comment]
Yes it's only present for legacy reasons, pre IPublishedElemet and our clients is used to it. 
We are going to add template-setting + angularfilter-setting (same  as NestedContent)
So the textbox will be disabled and autopopulated if a template is sett.

**Comment by stefankip** [comment]
Sounds good! 😎

Op za 23 mei 2020 10:44 schreef Dennis Öhman <notifications@github.com>:
